#!/bin/bash

# Set timezone to Asia/Jakarta
sudo timedatectl set-timezone Asia/Jakarta

# Update and upgrade the system
sudo apt update
sudo apt upgrade -y

# Install required packages
sudo apt install -y git curl zip python3 python3-pip

# Install Docker
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh

#Menhindari mengetik sudo setiap kali Anda menjalankan perintah docker
sudo usermod -aG docker $USER

# Clean up docker.sh
rm get-docker.sh

echo "Setup completed successfully."
